FROM  ubuntu:latest


USER root

ENV CATALINA_HOME /opt/tomcat
ENV PATH /opt/tomcat/bin:$PATH

RUN apt-get -y update && apt-get -y upgrade
RUN apt-get -y install openjdk-21-jdk wget


RUN mkdir -p /opt/tomcat
WORKDIR /opt/tomcat
#RUN groupadd tomcat
#RUN useradd -s /bin/bash -g tomcat -d /opt/tomcat tomcat

#ADD https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.85/bin/apache-tomcat-9.0.85.tar.gz .
#RUN tar -xvzf apache-tomcat-9.0.85.tar.gz
#RUN mv apache-tomcat-9.0.85/* /opt/tomcat

#RUN apt install wget -y 
#RUN wget https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.85/bin/apache-tomcat-9.0.85.tar.gz
#RUN tar -xf apache-tomcat-9.0.85.tar.gz -C /opt/tomcat --strip-components=1

RUN apt install wget -y 
RUN wget https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.18/bin/apache-tomcat-10.1.18.tar.gz
RUN tar -xf apache-tomcat-10.1.18.tar.gz -C /opt/tomcat --strip-components=1

#RUN chown -R tomcat:tomcat /opt/tomcat

COPY ./target/demovc.war /opt/tomcat/webapps/

#COPY ./METADATA/context.xml /opt/tomcat/webapps/examples/META-INF/
#COPY ./METADATA/context.xml /opt/tomcat/webapps/demovc/META-INF/


EXPOSE 8080

#SHELL ["/bin/bash", "-c"]
CMD ["/opt/tomcat/bin/catalina.sh","run"]